version: '3.8'
services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}
    restart: unless-stopped
volumes:
  db: {}
